spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: produce
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8083